package com.xworkz.vehicle;

import com.xworkz.vehicle.dao.VehicleDAO;
import com.xworkz.vehicle.entity.VehicleEntity;

public class VehicleRunner {
    public static void main(String[] args) {

        System.out.println("Initializing VehicleRunner Execution...");
        VehicleDAO dao = new VehicleDAO();

        // --- STEP 1: CREATE (C in CRUD) ---
        System.out.println("\n--- Creating New Vehicle Entity ---");
        VehicleEntity v1 = new VehicleEntity();
        v1.setRegistrationNumber("KA-01-MJ-2026");
        v1.setModel("Tesla Model 3");
        v1.setOwnerName("C Mallikarjun");
        v1.setTotalDistanceTravelled(120.5);

        // Setting values for @Transient fields (Runtime only)
        v1.setCurrentFuelLevel(85.0);
        v1.setLiveStatus("ACTIVE");

        System.out.println("Data Prepared. Sending to DAO for Persistence...");
        dao.registerVehicle(v1);

        System.out.println("Check 'transport_fleet_registry' table in MySQL.");
        System.out.println("Note: 'currentFuelLevel' and 'liveStatus' columns are absent due to @Transient.");

        // --- STEP 2: READ (R in CRUD) ---
        System.out.println("\n--- Testing Data Retrieval ---");
        // Assuming ID 1 is generated by MySQL
        VehicleEntity fetched = dao.getVehicle(1);

        if(fetched != null) {
            System.out.println("Record Found!");
            System.out.println("Vehicle Model: " + fetched.getModel());
            System.out.println("Owner: " + fetched.getOwnerName());

            // Verifying Transient behavior
            System.out.println("Current Fuel Level (from DB): " + fetched.getCurrentFuelLevel());
            System.out.println("Reason: The field exists in Java but was never mapped to a column.");
        } else {
            System.out.println("Error: Vehicle record not found. Ensure the ID is correct.");
        }

        System.out.println("\nVehicleRunner process finished.");
    }
}